name: tests

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: setup the env w/ micromamba
        uses: mamba-org/provision-with-micromamba@main

      - name: install code
        shell: bash -l {0}
        run: |
          python -m pip install -e .

      - name: lint
        shell: bash -l {0}
        run: |
          flake8 ssi_tools

      - name: test
        shell: bash -l {0}
        run: |
          pytest -vvs ssi_tools
